name: test-pr

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn compile
      - name: Run tests & coverage
        run: yarn coverage
